name: Running Test Batch 

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  check-bats-version:
    runs-on: windows-latest
    steps:
      # logs 브랜치로 checkout
      - name: origin/logs branch 
        uses: actions/checkout@v3
        with:
          ref: 'origin/logs'
          fetch-depth: '0'

      - uses: actions/checkout@v2
      - name: Create report file
        run: date /t  > report.txt
          
      # commit changes
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: "ChanwooPark-GGQ"
          author_email: "chanwoo.park@ggq.gg"
          message: 'Add Test Logs'
          add: 'report.txt'
          github_token: ${{ secrets.PUB_TOKEN }}
