name: Running Test Batch 

on:
  schedule:
    - cron: '*/10 * * * *'

jobs:
  check-bats-version:
    runs-on: windows-latest
    steps:
      # logs 브랜치로 checkout
      - name: origin/logs branch 
        uses: actions/checkout@v3
        with:
          ref: 'origin/logs'
          fetch-depth: '0'

      # batch file 실행
      - uses: actions/setup-node@v1
      - run: 
          npm install -g bats
          bats -v .\..\..\test.bat
          
      # commit changes
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: "ChanwooPark-GGQ"
          author_email: "chanwoo.park@ggq.gg"
          message: 'Add Test Logs'
          add: 'results.log'
          branch: 'origin/logs'
          github_token: ${{ secrets.PUB_TOKEN }}
