name: Test batch

on:
  schedule:
    - cron: '*/10 * * * *'

jobs:
  check-bats-version:
    runs-on: windows-latest
    steps:
      # logs 브랜치로 checkout
      - name: origin/logs branch 
        uses: actions/checkout@v2
        with:
          ref: 'origin/logs'
          fetch-depth: '0'

      # commit을 위한 git config 설정
      - name: Configure Git 
        run: |
          git config user.name "ChanwooPark-GGQ"
          git config user.email "chanwoo.park@ggq.gg"
          git pull
      
      # batch file 실행
      - uses: actions/setup-node@v1
      - run: 
          npm install -g bats
          bats -v .\..\..\test.bat

      - uses: ad-m/github-push-action@master
        with:
          branch: 'origin/logs'
          github_token: ${{ secrets.PUB_TOKEN }}