name: Test batch

on:
  schedule:
    - cron: '*/10 * * * *'

jobs:
  check-bats-version:
    runs-on: windows-latest
    steps:
      # logs 브랜치로 checkout
      - name: origin/logs branch 
        uses: actions/checkout@v3
        with:
          ref: 'origin/logs'
          fetch-depth: '0'

      # batch file 실행
      - uses: actions/setup-node@v1
      - run: 
          npm install -g bats
          bats -v .\..\..\test.bat

      # commit을 위한 git config 설정
      - name: Configure Git 
        run: |
          git config --global user.name "ChanwooPark-GGQ"
          git config --global user.email "chanwoo.park@ggq.gg"
          git pull

      - name: Commit report
        run: |
          git config --global user.name "ChanwooPark-GGQ"
          git config --global user.email "chanwoo.park@ggq.gg"
          git commit -m "Automated report"
          git add -A
          git push