name: Running Jmeter Test

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  check-bats-version:
    runs-on: windows-latest
    steps:
      # logs 브랜치로 checkout
      - name: origin/logs branch 
        uses: actions/checkout@v3
        with:
          ref: 'origin/logs'
          fetch-depth: '0'
      - run: cmd ${{ github.workspace }}\test.bat > ${{ github.workspace }}\result.log
        shell: cmd
      - run: dir ${{ github.workspace }}     
      # commit changes
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: "ChanwooPark-GGQ"
          author_email: "chanwoo.park@ggq.gg"
          message: 'Add Test Logs'
          add: 'result.log'
          github_token: ${{ secrets.PUB_TOKEN }}
