name: Running Jmeter Test

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      # logs 브랜치로 checkout
      - name: origin/logs branch 
        uses: actions/checkout@v3
        with:
          ref: 'origin/logs'
          fetch-depth: '0'
          
      - run: ${{ github.workspace }}/test > ${{ github.workspace }}/test_report/result.log
      - run: ls ${{ github.workspace }}     

      - name: Upload JMeter Test Results
        uses: actions/upload-artifact@v2.2.4
        with:
          name: test_results
          path: test_report
