name: Running Test Batch 

on:
  schedule:
    - cron: '*/10 * * * *'

jobs:
  check-bats-version:
    runs-on: windows-latest
    steps:
      # logs 브랜치로 checkout
      - name: origin/logs branch 
        uses: actions/checkout@v3
        with:
          ref: 'origin/logs'
          fetch-depth: '0'

      # batch file 실행
      - uses: actions/setup-node@v1
      - run: 
          npm install -g bats
          bats -v .\..\..\test.bat
          bats -v .\..\..\push.bat
