name: Git Push Batch

on:
  schedule:
    - cron: '*/10 * * * *'

jobs:
  check-bats-version:
    runs-on: windows-latest
    steps:
      # logs 브랜치로 checkout
      - name: origin/logs branch 
        uses: actions/checkout@v3
        with:
          ref: 'origin/logs'
          fetch-depth: '0'

      # commit을 위한 git config 설정

      - name: Commit report
        run: |
          git config --global user.name "ChanwooPark-GGQ"
          git config --global user.email "chanwoo.park@ggq.gg"
          git commit -m "Automated report"
          git add -A
          git push