name: Example Push Action
on: 
    push:
        branches: # 타겟 브랜치
            - 'origin/logs'
permissions:
  contents: write
jobs:
  build:
    runs-on: windows-latest
    steps:
        # batch file 실행
        - uses: actions/setup-node@v1
        - run: 
            npm install -g bats
            bats -v .\..\..\push.bat

        - uses: actions/checkout@v3
        - run: |
                git config --global user.name "ChanwooPark-GGQ"
                git config --global user.email "chanwoo.park@ggq.gg"
                
                git pull
                git checkout 'origin/logs'

                git add -A
                git commit -m "Add Test Logs"
                git push

        - name: Push changes to 'origin/logs' branch 
          uses: ad-m/github-push-action@master
          with:
            branch: 'origin/logs'
            github_token: ${{ secrets.PUB_TOKEN }}